---
  - hosts: search2
    become: true
    tasks:
      - copy:
          src: /home/scripts/search/search2.sh
          dest: /home/search2.sh

      - name: setting permission
        file: dest=/home/search2.sh mode=a+x

      - name: executing the script on remote machine
        shell: sh /home/search2.sh
        ignore_errors: yes
