---
  - hosts: search3
    become: true
    tasks:
      - copy:
          src: /home/scripts/search/search3.sh
          dest: /home/search3.sh

      - name: setting permission
        file: dest=/home/search3.sh mode=a+x

      - name: executing the script on remote machine
        shell: sh /home/search3.sh
        ignore_errors: yes
